//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avoir
    {
        public int IdEtab { get; set; }
        public int IdInfra { get; set; }
        public Nullable<int> Nombre { get; set; }
    
        public virtual Etablissement Etablissement { get; set; }
        public virtual Infrastrucutre Infrastrucutre { get; set; }
    }
}
