//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SCHOOLEntities1 : DbContext
    {
        public DB_SCHOOLEntities1()
            : base("name=DB_SCHOOLEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avoir> Avoir { get; set; }
        public virtual DbSet<Etablissement> Etablissement { get; set; }
        public virtual DbSet<Infrastrucutre> Infrastrucutre { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
